### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-luzm23#1]
[Infografía LIBRERIA Y COMPONENTTES DE C#.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-luzm23/files/11084727/Infografia.LIBRERIA.Y.COMPONENTTES.DE.C.pdf)

**Comment by Arlet04** [comment]
Partes de infografía: falta agregar fuentes 3
Coherencia:excelente 4
Organización: excelente 4
Diseño: excelente 4
Creatividad: excelente 4
Puntos: 19/20
Calificación: 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
